routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Site'], function (){
	Route::get('/','HomeController@index' )->name('index');
	Route::get('/service', 'HomeController@service')->name('service.list');
	Route::get('/service/{slug}', 'HomeController@serviceDetail')->name('service');
	Route::get('/projects', 'HomeController@project')->name('projects');
	Route::get('/project/all', 'HomeController@allProjectList')->name('all.project.list');
	Route::get('/project/{slug}', 'HomeController@projectDetail')->name('project.detail');
	Route::get('/posts', 'HomeController@newsList')->name('news.list');
	Route::get('/posts/{slug}', 'HomeController@newsDetail')->name('news.detail');
	Route::get('/category/{slug}', 'HomeController@newsCategoryList')->name('news.category');
	Route::get('/faq', 'HomeController@faqList')->name('faq');
	Route::get('/testimonial', 'HomeController@testimonialList')->name('testimonial');
	Route::get('/about-us', 'HomeController@aboutUs')->name('aboutus');
	Route::get('/contact-us', 'HomeController@contactUs')->name('contactus');
	Route::post('/post-contact-info', 'HomeController@postContactInfo')->name('post.contact_info');
	Route::post('/post-user-service', 'HomeController@postUserService')->name('post.user_service');
	Route::get('/teams', 'HomeController@teamList')->name('teams');
	Route::post('/newsletter', 'HomeController@newsLetter')->name('newsletter');
	Route::post('/search', 'HomeController@getSearchData')->name('searchdata');
	Route::get('/search', 'HomeController@getSearchDataPage')->name('searchdatapage');


	// unused
	Route::get('/page/{slug}', 'HomeController@pageDetail')->name('page.detail');

	Route::get('/content/{slug}', 'HomeController@contentDetail')->name('content.detail');
	Route::get('/client-profile/{slug}', 'HomeController@clientProfileDetail')->name('client_profile.detail');

	Route::get('/detail/{slug}', 'HomeController@postDetail')->name('post.detail');


	Route::get('/get-started', 'HomeController@getStarted')->name('getstarted');
	Route::post('/post-get-started', 'HomeController@postGetStarted')->name('post.get_started');
});






// Admin Web Route
Route::group(['prefix' => 'mdm-admin','namespace' => 'admin'], function (){
	Route::get('login', 'AdminLoginController@login')->name('login.page');
	Route::get('newsletter/{id}', 'AdminNewsletterController@show')->name('newsletterdetail');
	Route::post('login', 'AdminLoginController@loginCheck')->name('logincheck');
});

Route::group(['prefix' => 'u-admin', 'namespace' => 'admin', 'middleware'   => ['adminlogincheck','roles']], function (){
	Route::get('registeruser', 'AdminLoginController@userRegister')->name('user.create');
	Route::post('registeruser', 'AdminLoginController@userRegisterData')->name('userregister');
	Route::get('dashboard', 'AdminDashboardController@dashboard')->name('dashboard');
	Route::get('user/list', 'AdminLoginController@adminUserList')->name('user.list');
	Route::get('user/{id}/edit', 'AdminLoginController@editUser')->name('user.edit');
	Route::any('updateuser/{id}', 'AdminLoginController@updateuser')->name('user.update');
	Route::get('user/delete/{id}', ['as' => 'user.delete', 'uses' => 'AdminLoginController@deleteUser']);
	Route::any('logout', 'AdminLoginController@logout')->name('logout');

	Route::any('updateuserprofile/{id}', 'AdminProfileController@updateuser')->name('userprofile.update');
	Route::get('userprofile/{id}/edituserprofile', 'AdminProfileController@editUserProfile')->name('userprofile.editprofile');

	Route::get('success-login', 'AdminSiteSettingController@successLogin')->name('successlogin');
	Route::get('fail-login', 'AdminSiteSettingController@failLogin')->name('faillogin');
	Route::get('menu', 'AdminMenuController@index')->name('menu');

	// User Group
	Route::resource('usergroup', 'AdminGroupController');
	Route::get('usergroup/delete/{id}', ['as' => 'usergroup.delete', 'uses' => 'AdminGroupController@destroy']);

	// Role Access
	Route::resource('role-access', 'AdminRoleAccessController');
	Route::get('role-access/delete/{id}', ['as' => 'role-access.delete', 'uses' => 'AdminRoleAccessController@destroy']);
    Route::get('roleChangeAccess/{allowId}/{id}','AdminRoleAccessController@changeAccess');
    Route::get('setting','AdminSiteSettingController@setting')->name('setting');
    Route::post('setting-update','AdminSiteSettingController@updateSetting')->name('update.setting');

    // others
	Route::get('medialibrary', 'AdminDashboardController@mediaLibrary')->name('medialibrary');
	Route::any('ajax/drag-drop-sorting', 'AdminAjaxController@postDragDropSorting')->name('ajax.sorting');
	Route::any('module-url','AdminAjaxController@moduleUrl')->name('moduleUrl');


	// contra-admin

    // slider
	Route::resource('slider', 'AdminSliderController');
	Route::get('slider/delete/{id}', ['as' => 'slider.delete', 'uses' => 'AdminSliderController@destroy']);

	// Service
	Route::resource('service', 'AdminServiceController');
	Route::get('service/delete/{id}', ['as' => 'service.delete', 'uses' => 'AdminServiceController@destroy']);

    // Web Service
	Route::resource('web_services', 'AdminWebServiceController');
	Route::get('web_services/delete/{id}', ['as' => 'web_services.delete', 'uses' => 'AdminWebServiceController@destroy']);

    // Working Process
	Route::resource('working_process', 'AdminWorkingProcessController');
	Route::get('working_process/delete/{id}', ['as' => 'working_process.delete', 'uses' => 'AdminWorkingProcessController@destroy']);

	// Home Icon
	Route::resource('homeicon', 'AdminHomeIconController');
	Route::get('homeicon/delete/{id}', ['as' => 'homeicon.delete', 'uses' => 'AdminHomeIconController@destroy']);

	// about_content
	Route::resource('about_content', 'AboutContentController');
	Route::get('about_content/delete/{id}', ['as' => 'about_content.delete', 'uses' => 'AboutContentController@destroy']);

	// testimonial
	Route::resource('testimonial', 'TestimonialController');
	Route::get('testimonial/delete/{id}', ['as' => 'testimonial.delete', 'uses' => 'TestimonialController@destroy']);

    // client
	Route::resource('client', 'ClientController');
	Route::get('client/delete/{id}', ['as' => 'client.delete', 'uses' => 'ClientController@destroy']);

	// teams
	Route::resource('team', 'TeamController');
	Route::get('team/delete/{id}', ['as' => 'team.delete', 'uses' => 'TeamController@destroy']);

	// // service
	// Route::resource('service', 'ServiceController');
	// Route::get('service/delete/{id}', ['as' => 'service.delete', 'uses' => 'ServiceController@destroy']);

	//You should Know in Service
	Route::resource('service-wise-point', 'ServiceWisePointController');
	Route::get('service-wise-point/delete/{id}', ['as' => 'service-wise-point.delete', 'uses' => 'ServiceWisePointController@destroy']);

	// project category
	Route::resource('project-category', 'AdminProjectCategoryController');
	Route::get('project-category/delete/{id}', ['as' => 'project-category.delete', 'uses' => 'AdminProjectCategoryController@destroy']);

	// project
	Route::resource('project', 'AdminProjectController');
	Route::get('project/delete/{id}', ['as' => 'project.delete', 'uses' => 'AdminProjectController@destroy']);

	// author
	Route::resource('author', 'AdminAuthorController');
	Route::get('author/delete/{id}', ['as' => 'author.delete', 'uses' => 'AdminAuthorController@destroy']);

	// category
	Route::resource('category', 'AdminCategoryController');
	Route::get('category/delete/{id}', ['as' => 'category.delete', 'uses' => 'AdminCategoryController@destroy']);

	// posts
	Route::resource('posts', 'AdminPostsController');
	Route::get('posts/delete/{id}', ['as' => 'posts.delete', 'uses' => 'AdminPostsController@destroy']);






	// Partner
	Route::resource('partner', 'PartnerController');
	Route::get('partner/delete/{id}', ['as' => 'partner.delete', 'uses' => 'PartnerController@destroy']);






	// Contact
	Route::resource('contact', 'AdminContactController');
	Route::get('contact/delete/{id}', ['as' => 'contact.delete', 'uses' => 'AdminContactController@destroy']);

	// Pages
	Route::resource('pages', 'AdminPagesController');
	Route::get('pages/delete/{id}', ['as' => 'pages.delete', 'uses' => 'AdminPagesController@destroy']);

	// FAQ
	Route::resource('faq', 'AdminFaqController');
	Route::get('faq/delete/{id}', ['as' => 'faq.delete', 'uses' => 'AdminFaqController@destroy']);







	// upto here

	// newsletter
	// Route::get('newsletter/email-list', ['as' => 'newsletter.emaillist', 'uses' => 'AdminNewsletterController@emailList']);

	Route::get('newsletter/resendmail/{id}', ['as' => 'newsletter.resendmail', 'uses' => 'AdminNewsletterController@resendMail']);

	Route::get('newsletter/status-change/{id}', 'AdminNewsletterController@newsletterStatusUpdate');

	// newsletter subscription
	Route::resource('newsletter', 'AdminNewsletterController');
	Route::get('newsletter-subscription', 'AdminNewsletterController@subscriptionList')->name('newsletter.subscription');
	Route::get('newsletter-subscription/{id}', 'AdminNewsletterController@show')->name('newsletter-subscription.show');

	// use service
	Route::get('user-service', 'AdminUserServiceController@list')->name('user_service.index');
	Route::get('user-service/status-change/{id}', 'AdminUserServiceController@userServiceStatusUpdate');

});

resources/views/admin/home.blade.php
@extends('admin.master')
@section('title', $page_header)
@section('content-header', $page_header)
@section('content')
   {{-- <div class="card">
	<div class="card-header">{{ $page_header }}</div>
	<div class="card-body">
	    <h4>Welcome to Dashboard</h4>
	</div>
</div> --}}
   <div class="main-top-dashboard ">
      <div class="row no-gutters">
         {{-- <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 dashboard-list">
                <div class="card project-card">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="project-content">
                                <a href="{{ route('request_client.index') }}">
                                	<h6>Client Request</h6>
	                                <ul>
	                                     <li>
	                                        <strong>New Client Request</strong>
	                                        <span class='new_client_request'>{{ $new_client_request }}</span>

	                                    </li>
	                                    <li>
	                                        <strong>Viewed Client Request</strong>
	                                        <span class='view_client_request'>{{ $view_client_request }}</span>

	                                    </li>
	                                    <li>
	                                        <strong>Blocked Client Request</strong>
	                                        <span class='blocked_client_request'>{{ $blocked_client_request }}</span>

	                                    </li>

	                                </ul>
	                            </a>
                            </div>

                            <div class="ml-auto">
                                <div class="dashboard-icon icon-1">
                                    <i class="fa fa-file-text-o" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> --}}
         <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 dashboard-list">
            <div class="card project-card">
               <div class="card-body">
                  <div class="d-flex">
                     <div class="project-content">
                        <a href="{{ route('newsletter.index') }}">
                           <h6>Newsletter</h6>
                           <ul>
                              <li>
                                 <strong>New </strong>
                                 <span>{{ $new_newsletter }}</span>
                              </li>
                              <li>
                                 <strong>Active</strong>
                                 <span>{{ $active_newsletter }}</span>
                              </li>
                              <li>
                                 <strong>Blocked</strong>
                                 <span>{{ $blocked_newsletter }}</span>
                              </li>
                           </ul>
                        </a>
                     </div>

                     <div class="ml-auto">
                        <div class="dashboard-icon icon-3">
                           <i class="fa fa-envelope" aria-hidden="true"></i>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 dashboard-list">
            <div class="card project-card">
               <div class="card-body">
                  <div class="d-flex">
                     <div class="project-content">
                        <a href="{{ route('project.index') }}">
                           <h6>Projects</h6>
                           <ul>
                              <li>
                                 <strong>Total</strong>
                                 <span>{{ $projects }}</span>
                              </li>
                           </ul>
                        </a>
                     </div>

                     <div class="ml-auto">
                        <div class="dashboard-icon icon-2">
                           <i class="fa fa-cubes" aria-hidden="true"></i>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 dashboard-list">
            <div class="card project-card">
               <div class="card-body">
                  <div class="d-flex">
                     <div class="project-content">
                        <a href="{{ route('testimonial.index') }}">
                           <h6>Testimonial</h6>
                           <ul>
                              <li>
                                 <strong>Total</strong>
                                 <span>{{ $testimonial }}</span>
                              </li>
                           </ul>
                        </a>
                     </div>

                     <div class="ml-auto">
                        <div class="dashboard-icon icon-2">
                           <i class="fa fa-users" aria-hidden="true"></i>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 dashboard-list">
            <div class="card project-card">
               <div class="card-body">
                  <div class="d-flex">
                     <div class="project-content">
                        <a href="{{ route('contact.index') }}" target="_blank">
                           <h6>FeedBack</h6>
                           <ul>
                              <li>
                                 <strong>New</strong>
                                 <span>{{ $new_feedback }}</span>

                              </li>
                              <li>
                                 <strong>Viewed</strong>
                                 <span>{{ $viewed_feedback }}</span>

                              </li>
                              <li>

                              </li>
                           </ul>
                        </a>
                     </div>

                     <div class="ml-auto">
                        <div class="dashboard-icon icon-3">
                           <i class="fa fa-comment" aria-hidden="true"></i>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>

@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>|| Admin Login ||</title>
        <link rel="icon" type="image/png" href="{{ asset($sitedetail->logo) }}" sizes="any"/>

        <!-- Icons-->
        <link href="{{ asset('admin/vendors/@coreui/icons/css/coreui-icons.min.css') }}" rel="stylesheet">
        <link href="{{ asset('admin/vendors/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
        <link href="{{ asset('admin/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ asset('admin/vendors/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
        <!-- Main styles for this application-->
        <link href="{{ asset('admin/css/style.css') }}" rel="stylesheet">
        {{-- <link href="{{ asset('admin/vendors/pace-progress/css/pace.min.css') }}" rel="stylesheet"> --}}
    </head>
    <body class="app flex-row align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card-group">
                        <div class="card p-4">
                            <div class="card-body">
                                <h1>Log In</h1>
                                <p class="text-muted">Sign In to your account</p>
                                @if (Session::has('message'))
                                <div class="alert alert-danger alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    {{ Session::get('message') }}
                                </div>
                                @endif
                                <form action="{{ route('logincheck') }}" method="POST">
                                    {{ csrf_field() }}
                                    <div class="input-wrap">
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-user"></i>
                                                </span>
                                            </div>
                                            <input class="form-control"  name="username" type="text" placeholder="Username" value="{{ old('username')}}">
                                            
                                        </div>
                                        @if ($errors->has('username'))
                                        <p class="text-danger">{{ $errors->first('username') }}</p>
                                        @endif
                                        
                                    </div>
                                    <div class="input-wrap">
                                        <div class="input-group mb-4">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">
                                                    <i class="icon-lock"></i>
                                                </span>
                                            </div>
                                            <input type="password" class="form-control" name="password" placeholder="Password">
                                        </div>
                                        @if ($errors->has('password'))
                                        <p class="text-danger">{{ $errors->first('password') }}</p>
                                        @endif
                                    </div>
                                    {{-- <div class="input-wrap">
                                        <div class="input-group mb-4">
                                        {!! app('captcha')->display() !!}
                                        </div>
                                        @if ($errors->has('g-recaptcha-response'))
                                        <p class="text-danger">{{ $errors->first('g-recaptcha-response') }}</p>
                                        @endif
                                    </div> --}}
                                    <div class="row">
                                        <div class="col-6">
                                            <button class="btn btn-primary px-4" type="submit">Login</button>
                                        </div>
                                        <div class="col-6 text-right">
                                            {{-- <button class="btn btn-link px-0" type="button">Forgot password?</button> --}}
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card bg-secondary py-5 d-md-down-none" style="width:44%">
                            <div class="card-body text-center">
                                <div>
                                    @if($sitedetail->title)
                                    <p>{{ $sitedetail->title}}</p>
                                    @else
                                    <p>Site Name</p>
                                    @endif
                                    @if($sitedetail->logo)
                                    <img src="{{ asset($sitedetail->logo) }}" style="max-width: 100%; height: 150px;">
                                    @else
                                    <img src="{{ asset('uploads/default/default-website.png') }}" style="max-width: 100%; height: 150px;">
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- CoreUI and necessary plugins-->
        <script src="{{ asset('admin/vendors/jquery/js/jquery.min.js') }}"></script>
        <script type="text/javascript" src="https://www.google.com/recaptcha/api.js"></script>
    </body>
</html>

resources/views/admin/master.blade.php
<!DOCTYPE html>
<html lang="en">
    @include('admin.layouts.meta')
    <body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show" id="top-header">
        @include('admin.layouts.header')
        <div class="app-body">
            @include('admin.layouts.menu')
            <main class="main mbottom10">
                <div class="container-fluid">
                    <div class="animated fadeIn">
                        <div class="row">
                            <div class="col-md-12">
                                @if (Session::has('message'))
                                <div class="alert alert-danger alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    {{ Session::get('message') }}
                                </div>
                                @endif
                                @if (Session::has('success_message'))
                                <div class="alert alert-success alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                    {{ Session::get('success_message') }}
                                </div>
                                @endif
                            </div>
                        </div>
                        @section('content')
                        @show
                    </div>
                </div>
            </main>
        </div>
        @include('admin.layouts.footer')
        @include('admin.layouts.script')
    </body>
</html>

resources/views/admin/medialibrary.blade.php
@extends('admin.master')
@section('title', $page_header)
@section('content-header', $page_header)
@section('content')

<iframe src="{{ url('/uploads/filemanager/dialog.php?type=1&field_id=image') }}" width="100%" height="500px"></iframe>
@endsection